@startuml

object "<u>instructor1:Instructor</u>" as ins1 {
    firstName = "Nima"
    lastName = "Davarpanah"
    officeNumber = "3-2636"
}

object "<u>instructor2:Instructor</u>" as ins2 {
    firstName = "John"
    lastName = "Doe"
    officeNumber = "3-2637"
}

object "<u>textbook1:Textbook</u>" as txt1 {
    title = "Clean Code"
    author = "Robert C. Martin"
    publisher = "Pearson"
}

object "<u>textbook2:Textbook</u>" as txt2 {
    title = "Effective Java"
    author = "Joshua Bloch"
    publisher = "Addison-Wesley"
}

object "<u>course1:Course</u>" as crs1 {
    courseName = "Software Engineering"
}

object "<u>course2:Course</u>" as crs2 {
    courseName = "Data Structures"
}

crs1 o-- ins1
crs1 o-- txt1
crs2 o-- ins2
crs2 o-- txt2

@enduml
