@startuml

object "<u>php_demo1:Folder</u>" as demo1 {
    name = "php_demo1"
}
object "<u>source_files:Folder</u>" as src {
    name = "Source Files"
}
object "<u>cache:Folder</u>" as cache {
    name = "cache"
}
object "<u>public_folder:Folder</u>" as public {
    name = "public"
}
object "<u>phalcon:Folder</u>" as phal {
    name = ".phalcon"
}
object "<u>htaccess:File</u>" as htac {
    name = ".htaccess"
}
object "<u>htrouter:File</u>" as htr {
    name = ".htrouter.php"
}
object "<u>index:File</u>" as idx {
    name = "index.html"
}
demo1 *-- src
src *-- phal
src *-- cache
src *-- public
src *-- htac
src *-- htr
src *-- idx

@enduml
