@startuml

object Ship
object CruiseShip
object CargoShip

map ships {
    0 => Ship
    1 => CruiseShip
    2 => CargoShip
}
object Ship {
    name = "Ship1"
    yearBuilt = "2000"
    maxPassangers = 1000
}
object CruiseShip {
    name = "CruiseShip1"
    yearBuilt = "2010"
    maxPassangers = 500
}
object CargoShip {
    name = "CargoShip1"
    yearBuilt = "2020"
    maxPassangers = 10000
}
Ship --> ships::0
CruiseShip --> ships::1
CargoShip --> ships::2
@enduml